<?php

namespace Tests\Feature;

use App\Enums\Roles;
use App\Models\Restaurant;
use App\Models\User;
use Database\Seeders\RoleSeeder;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use PHPUnit\Framework\Attributes\Test;
use Tests\TestCase;

class AdminTest extends TestCase
{
    use RefreshDatabase;

    protected Restaurant $restaurant;

    #[Test]
    public function admin_user_can_delete_any_restaurant(): void
    {
        $admin = User::factory()->create();
        $admin->assignRole(Roles::ADMIN->value);
        $response = $this->apiAs($admin, 'delete', "{$this->apiBase}/restaurants/{$this->restaurant->id}");

        $response->assertStatus(200);
        $this->assertSoftDeleted('restaurants', [
            'id' => $this->restaurant->id,
        ]);

    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->seed(RoleSeeder::class);
        $this->restaurant = Restaurant::factory()->create();
    }
}
